_target_: pytorch_lightning.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 30
check_val_every_n_epoch: 1
strategy: ddp
accelerator: gpu

num_nodes: 1


precision: 16



deterministic: False

