


root_dir: ${oc.env:PROJECT_ROOT}
project_task: ${oc.env:PROJECT_TASK}
repo_root: ${oc.env:REPO_ROOT}


data_dir: ${oc.env:DATA_ROOT}


log_dir: ${hydra:runtime.output_dir}




output_dir: ${hydra:runtime.output_dir}


work_dir: ${hydra:runtime.cwd}
