


defaults:
  - override hydra_logging: custom_logger
  - override job_logging: custom_logger


run:
  dir: ${oc.env:LOG_ROOT}/${prefix}-${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${oc.env:LOG_ROOT}/${prefix}-${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}
